### ISSUE TITLE
Trainingdata

### ISSUE THREAD

**Issue by cswwp** [multunus/autonomous-rc-car#1]
hi, i'm learning this project,and i want to get the training data in this program, because it's too waste time to collect training data with manually operate the car, so do you mind to give your training data or upload the training data?

**Comment by yedhukrishnan** [comment]
@vimalvnair @Vignesh1115 ☝️

**Comment by Vignesh1115** [comment]
@cswwp Sorry for the delay, you can find the dataset here - https://s3.amazonaws.com/multunus-machine-learning/autonomous-rc-car-data-set.tar.gz . Please let me know if you need anything.

**Comment by cswwp** [comment]
@Vignesh1115 i'm very pleased to receive your reply, and also thank you for your dataset.

**Comment by Vignesh1115** [comment]
Thank you for your kind words @cswwp. Let me know if you need help with anything. I will be closing this issue.
