### ISSUE TITLE
Getting error in Train.py

### ISSUE THREAD

**Issue by BilalAh** [multunus/autonomous-rc-car#11]
Hello,Sir i'm getting error when i run Train.py.
FileNotFoundError:No such File or Directory: Optimized_thetas/model_2017-05-29_21-08-44_10.0_h50.pkl

**Comment by BilalAh** [comment]
![optimized_theta](https://cloud.githubusercontent.com/assets/28658501/26596489/4d8e03d8-4588-11e7-819b-8dc302715eb7.PNG)

**Comment by Vignesh1115** [comment]
Hi @BilalAh, This error is caused by the absence of the `optimized_thetas` directory. The commit 048d983 fixes the issue.
