### ISSUE TITLE
ImportError: No module named 'scipy'

### ISSUE THREAD

**Issue by manivannan0212** [multunus/autonomous-rc-car#19]
I am facing this issue :

Traceback (most recent call last):
  File "train.py", line 11, in <module>
    from scipy.optimize import fmin_l_bfgs_b
ImportError: No module named 'scipy'

**Comment by yedhukrishnan** [comment]
Did you try `pip install scipy` from the command line?

**Comment by manivannan0212** [comment]
Thank you , this error is sorted out after installing scipy " pip install scipy "
