### ISSUE TITLE
Is there any pre-trained model

### ISSUE THREAD

**Issue by GZJackCai** [multunus/autonomous-rc-car#2]
hi, i'm learning this project,I downloaded  the dataset-https://s3.amazonaws.com/multunus-machine-learning/autonomous-rc-car-data-set.tar.gz.My computer is not very powerful , can someone or could give a link where we can download a pre-trained model?

**Comment by Vignesh1115** [comment]
Hi @GZJackCai, you can find a pre-trained model here - https://s3.amazonaws.com/multunus-machine-learning/model_2016-07-20_19-38-07_l0.05_h114.pkl. Place the model in the `optimized_thetas` folder. Please let me know if you need help with anything.

**Comment by GZJackCai** [comment]
@Vignesh1115 ,i'm very pleased to receive your reply, and also thank you for your pre-trained model!

**Comment by Vignesh1115** [comment]
@GZJackCai I'm glad the pre-trained model helped, let me know if you need anything. I will be closing this issue.
