### ISSUE TITLE
camera no video

### ISSUE THREAD

**Issue by dantinr** [multunus/autonomous-rc-car#3]
when python interactive_control_train.py,there's no video from camera ,but images can generate into the folder ,what's wrong?

**Comment by Vignesh1115** [comment]
Hi @dantinr, we are not recording the video in either `interactive_control_train.py` or `autonomous.py`, this [section](http://picamera.readthedocs.io/en/release-1.12/recipes2.html#capturing-images-whilst-recording) should help you get started on capturing images whilst recording the video.

**Comment by dantinr** [comment]
THX @Vignesh1115 , I'll try, have a nice day

**Comment by Vignesh1115** [comment]
Thank you @dantinr, I hope the link helped you record video while capturing images. Let me know if you need help with anything. I will be closing this issue.
