### ISSUE TITLE
When do you plan to add new features

### ISSUE THREAD

**Issue by 99unicorn** [multunus/autonomous-rc-car#4]
When do you plan to add stop signal detection and obstacle detection?

**Comment by Vignesh1115** [comment]
Hi @99unicorn,
I'll discuss this with my team and post an update here by tomorrow.

**Comment by 99unicorn** [comment]
Thank you for the information.

**Comment by vimalvnair** [comment]
Hi @99unicorn , 
We do not have any immediate plans to work on those features. But, if you are keen on doing it, we can help you.
