### ISSUE TITLE
PyGame is not Working 

### ISSUE THREAD

**Issue by isrugeek** [multunus/autonomous-rc-car#7]
Why PyGame is not working in my Raspberry PI!?
`    while True:
        for event in pygame.event.get():
            if event.type in {pygame.K_q, pygame.K_ESCAPE}:
                print "Bye"
            elif event.type in {pygame.KEYDOWN, pygame.KEYUP}:
                print "Key pressed"
                if event.type == pygame.KEYUP:

                    print "UP"`

This is my Sample Code ! Actually it shows in terminal just random texts rather than UP
Thanks in Advance

**Comment by Vignesh1115** [comment]
@isrugeek Could you provide more details about this issue? Did you face this while running `train.py`?

**Comment by isrugeek** [comment]
@Vignesh1115 to be honest it's not related to your work but i was doing same project and faced some error in PyGame that's why ! but i appreciate your work as well as Reply! i am doing similar work like you ( Autonomous Car) i will ask any error questions here ! 
Thanks folk! 

**Here: i fixed my py game by giving some windows! to execute!**

**Comment by isrugeek** [comment]
@Vignesh1115 by the way how could your training images and data set can be same for the others?
because they actual data may differ in terms of their camera, realtime effects and more !

**Comment by Vignesh1115** [comment]
@isrugeek The dataset is highly unlikely to be the same; lots of parameters like camera angle, lighting etc. can always differ. The [training dataset](https://s3.amazonaws.com/multunus-machine-learning/autonomous-rc-car-data-set.tar.gz) was provided so that our users could use it to augment their existing datasets to get started with the training faster and then tune it as they generate more training images.

**Comment by isrugeek** [comment]
@Vignesh1115 you mean as a reference? right?

**Comment by Vignesh1115** [comment]
@isrugeek Yes, that's correct.

**Comment by isrugeek** [comment]
great! Source Code! i was seeing your code! to save the images in correct path try to re write `images.py` 
`path = direction`
`image.save(path+'/image%s.jpg' % ("-" + direction + "-"+ str(time.time())), format="JPEG")`
so it will add to desired folder with out error! also more folders must be created like forward_right , forward_left.. etc

but i can't understand one thing here! in `interactive_control.py` the loop then how ever you pressed esc or q it won't quit i just tried using Jupyter! of course it must work!

cheers

**Comment by isrugeek** [comment]
@Vignesh1115 yes! even i download your code and when i press q or esc it wont exit!!! i faced this issue in pygame also!

**Comment by Vignesh1115** [comment]
@isrugeek You can quit `interactive_control.py` using `Ctrl-C` or similar commands to stop the python script.

**Comment by isrugeek** [comment]
forcing quit pyhton script ?? it doesn't have any effects on data??

 `os.exit()` may be works too!
